### ISSUE TITLE
with fbcunn, cutorch.test() only works with Titan X?

### ISSUE THREAD

**Issue by jiajunwu** [facebook/fbcunn#93]
After installing fbcunn, I notice many tests in cutorch.test() fail on my machine. For instance, functions like fill(), zeros() all fail with error messages like:

install/share/lua/5.1/cutorch/test.lua:602: cuda runtime error (8) : invalid device function at torch/extra/cutorch/lib/THC/THCTensorMath.cu:318

I notice this problem with Titan and K40... For a different machine with Titan X, the same installation works fine and passes all tests.

**Comment by WendyShang** [comment]
@jiajunwu I run into the same issue; may I ask how did you resolve it? Thanks!

**Comment by jiajunwu** [comment]
I ended up reinstalling torch on a machine with Titan X (before it was installed on a machine with only Titan), and it works fine for all GPUs.
